.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH handlr-open 1  "open " 
.SH NAME
handlr\-open \- Open a path/URL with its default handler
.SH SYNOPSIS
\fBhandlr open\fR [\fB\-s\fR|\fB\-\-selector\fR] [\fB\-e\fR|\fB\-\-enable\-selector\fR] [\fB\-d\fR|\fB\-\-disable\-selector\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPATHS\fR> 
.SH DESCRIPTION
Open a path/URL with its default handler
.PP
Unlike xdg\-open and similar resource openers, multiple paths/URLs may be supplied.
.PP
If multiple handlers are set and `enable_selector` is set to true, you will be prompted to select one using `selector` from ~/.config/handlr/handlr.toml. Otherwise, the default handler will be opened.
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-selector\fR=\fISELECTOR\fR
Override the configured selector command
.TP
\fB\-e\fR, \fB\-\-enable\-selector\fR
Enable selector, overrides `enable_selector`
.TP
\fB\-d\fR, \fB\-\-disable\-selector\fR
Disable selector, overrides `enable_selector`
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
<\fIPATHS\fR>
Paths/URLs to open
