.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH handlr-launch 1  "launch " 
.SH NAME
handlr\-launch \- Launch the handler for specified extension/mime with optional arguments
.SH SYNOPSIS
\fBhandlr launch\fR [\fB\-s\fR|\fB\-\-selector\fR] [\fB\-e\fR|\fB\-\-enable\-selector\fR] [\fB\-d\fR|\fB\-\-disable\-selector\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIMIME\fR> [\fIARGS\fR] 
.SH DESCRIPTION
Launch the handler for specified extension/mime with optional arguments
.PP
Only supports wildcards for mimetypes for handlers that have been set or added with wildcards.
.PP
If multiple handlers are set and `enable_selector` is set to true, you will be prompted to select one using `selector` from ~/.config/handlr/handlr.toml. Otherwise, the default handler will be opened.
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-selector\fR=\fISELECTOR\fR
Override the configured selector command
.TP
\fB\-e\fR, \fB\-\-enable\-selector\fR
Enable selector, overrides `enable_selector`
.TP
\fB\-d\fR, \fB\-\-disable\-selector\fR
Disable selector, overrides `enable_selector`
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
<\fIMIME\fR>
Mimetype or file extension to launch the handler of
.TP
[\fIARGS\fR]
Arguments to pass to handler program
